# Profile file. Runs on login. Environement variables are set here.

# Default programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export READER="okular"
export FILE="vifm"

# ~/ Clean-up:
export LESSHISTFILE="-"

# Start Xorg
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
