# Profile file. Runs on login. Environement variables are set here.

# Default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export READER="zathura"
export FILE="vifm"

# ~/ Clean-up:
export ZDOTDIR="$HOME/.config/zsh"
export LESSHISTFILE="-"

