#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap dk &
xrandr --output DP-2 --primary --output DP-1 --left-of DP-2 &
picom &
exec dwm
