#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap dk &
xrandr --output DP-1 --primary --mode 1920x1080 --output DP-2 --left-of DP-1
picom &
feh --bg-scale --no-fehbg $HOME/pictures/wallpapers/lines.jpg
exec i3
